import type { SceneDocument } from '@w3/schema'
import { createGoldenPathDocument } from '@w3/schema'
import type { AssetResolver } from '@w3/storage'
import { AssetLoader, auditGlb, buildSamplePumpGlb } from '@w3/core'
import type { StorageProvider } from '@w3/storage'
import { IndexedDbProvider, MemoryProvider, extensionOf, hashBytes, hashToPath, pathToHash } from '@w3/storage'

/**
 * The project session — one storage provider, one resolver, one loader, for the whole
 * editor.
 *
 * This file exists because of a bug, and the bug is worth recording. The viewport used to
 * build its runtime with `createMemoryResolver(new Map())` while the asset panel kept its
 * own module-level `MemoryProvider` and `AssetLoader`. Both halves worked. Importing a GLB
 * ran a full health check, grew the hierarchy tree, grew the asset list, and advanced the
 * object count in the status bar — and the viewport never showed a single triangle,
 * because the bytes went into one loader and the renderer read from the other. Every
 * signal said success; only the picture disagreed.
 *
 * So: exactly one owner of asset bytes, handed to everything that needs them (C7 — the
 * rest of the editor sees `StorageProvider` and never IndexedDB).
 */

export interface ProjectSessionOptions {
  /** Injected by tests. Defaults to IndexedDB, falling back to memory. */
  readonly storage?: StorageProvider
}

export class ProjectSession {
  readonly storage: StorageProvider
  readonly resolver: AssetResolver
  readonly loader: AssetLoader

  /**
   * Bytes for a url the storage layer cannot address.
   *
   * Kept as a fallback for anything that arrives without a content hash. The sample no
   * longer needs it — see `materialiseSample`.
   */
  private readonly overlay = new Map<string, ArrayBuffer>()

  constructor(options: ProjectSessionOptions = {}) {
    this.storage = options.storage ?? defaultStorage()
    this.resolver = {
      resolve: (url) => this.resolve(url),
    }
    this.loader = new AssetLoader({ resolver: this.resolver })
  }

  private async resolve(url: string): Promise<ArrayBuffer> {
    const overlaid = this.overlay.get(url)
    if (overlaid) return overlaid

    const hash = pathToHash(url)
    if (!hash) throw new Error(`无法解析资产地址（既不是内容寻址路径，也不在会话缓存中）：${url}`)

    const bytes = await this.storage.getBlob(hash)
    if (!bytes) throw new Error(`存储中找不到该资产的字节：${url}`)
    // Copy onto a standalone buffer: the view IndexedDB hands back may be a window onto a
    // larger one, and GLTFLoader reads the whole buffer.
    return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer
  }

  /** Serves bytes for a url the storage layer cannot address. */
  provide(url: string, bytes: ArrayBuffer): void {
    this.overlay.set(url, bytes)
  }

  /**
   * Turns the sample document's placeholder asset into a real, stored, publishable one.
   *
   * SCHEMA_SPEC §12's sample declares a fabricated hash and fabricated statistics
   * (`sha256:ab12…`, 128,400 triangles, 8.4 MB) for a file that has never existed. Serving
   * generated bytes at that url was enough to make the viewport work — and left the
   * project **unpublishable**, because the publish gate asks storage for the declared hash
   * and correctly reports that nothing is there. On a fresh install, that meant 发布 never
   * worked at all. The golden-path E2E is what found it.
   *
   * So the sample goes through the same path an import does: hash the bytes, store the
   * blob, and record the asset against what is actually there. The fabricated statistics
   * become measured ones as a side effect, which is the honest outcome — an asset panel
   * reporting 8.4 MB for a 3 KB file was misinformation either way.
   *
   * `createGoldenPathDocument` itself is untouched: this is the editor materialising a
   * placeholder, exactly as it would for any other asset, not an edit to a spec artifact.
   *
   * Gated on the project id rather than on "we could not resolve it". An imported asset
   * whose blob has gone missing must fail loudly; quietly substituting a pump for it would
   * turn data loss into a wrong picture, which is strictly worse.
   *
   * @returns the document to open — unchanged unless it is the sample.
   */
  async materialiseSample(doc: SceneDocument): Promise<SceneDocument> {
    if (doc.projectId !== SAMPLE_PROJECT_ID) return doc
    const index = doc.assets.findIndex((a) => a.type === 'model')
    const sample = doc.assets[index]
    if (!sample) return doc

    // Already materialised — a saved project keeps the real hash, so this is the
    // second-boot path and there is nothing to do.
    if (await this.storage.hasBlob(sample.hash)) return doc

    const bytes = await buildSamplePumpGlb()
    const view = new Uint8Array(bytes)
    const hash = await hashBytes(view)
    await this.storage.putBlob(view)

    const audit = await auditGlb(bytes)
    const assets = [...doc.assets]
    assets[index] = {
      ...sample,
      hash,
      url: hashToPath(hash, extensionOf(sample.name) || '.glb'),
      stats: audit.stats,
      audit: audit.audit,
    }
    return { ...doc, assets }
  }

  async save(doc: SceneDocument): Promise<void> {
    await this.storage.saveDocument(doc)
  }

  async load(projectId: string): Promise<SceneDocument | null> {
    return this.storage.loadDocument(projectId)
  }

  async dispose(): Promise<void> {
    this.loader.dispose()
    this.overlay.clear()
    await this.storage.close()
  }
}

/** SCHEMA_SPEC §12's sample. Read once rather than rebuilt on every boot. */
const SAMPLE_PROJECT_ID = createGoldenPathDocument().projectId

function defaultStorage(): StorageProvider {
  // The feature detection lives inside @w3/storage, and the C7 guard is right to insist:
  // the editor naming a browser API directly is exactly the coupling that makes the v1
  // swap to an HTTP provider a rewrite instead of a constructor change.
  //
  // Memory is a working editor that forgets on refresh; a crash on boot is not.
  return IndexedDbProvider.isSupported() ? new IndexedDbProvider() : new MemoryProvider()
}
